plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace = "com.unidad.ganadera.notario.module_app"
    compileSdk 35

    defaultConfig {
        minSdk 19
        targetSdk 35

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    kapt {
        arguments {
            arg("room.schemaLocation", "$projectDir/schemas")
        }
    }
}

dependencies {
    implementation libs.moshi
    testImplementation libs.junit
    androidTestImplementation libs.junit.test.ext
    androidTestImplementation libs.espressso.core
    implementation platform(libs.firebase.bom)
    // Firestore
    implementation libs.firebase.firestore.ktx
    // Room
    implementation libs.room.runtime
    implementation libs.room.ktx
    kapt libs.room.compiler
    implementation libs.hilt
    kapt libs.hilt.compiler
}